"""Shared expectations for notebook exercises."""

from __future__ import annotations

from tests.exercise_expectations.ex001_sanity import (
    EX001_FUNCTION_NAME,
    EX001_NOTEBOOK_PATH,
    EX001_TAG,
)
from tests.exercise_expectations.ex002_sequence_modify_basics_exercise_expectations import (
    EX002_EXPECTED_MULTI_LINE,
    EX002_EXPECTED_NUMERIC,
    EX002_EXPECTED_PRINT_CALLS,
    EX002_EXPECTED_SINGLE_LINE,
    EX002_NOTEBOOK_PATH,
)
from tests.exercise_expectations.ex003_sequence_modify_variables import (
    EX003_EXPECTED_INPUT_MESSAGES,
    EX003_EXPECTED_PROMPTS,
    EX003_EXPECTED_STATIC_OUTPUT,
    EX003_NOTEBOOK_PATH,
    EX003_ORIGINAL_PROMPTS,
)
from tests.exercise_expectations.ex004_sequence_debug_syntax import (
    EX004_EXPECTED_SINGLE_LINE,
    EX004_FORMAT_VALIDATION,
    EX004_MIN_EXPLANATION_LENGTH,
    EX004_NOTEBOOK_PATH,
    EX004_PLACEHOLDER_PHRASES,
    EX004_PROMPT_STRINGS,
)
from tests.exercise_expectations.ex005_sequence_debug_logic import (
    EX005_AVERAGE_DIVISOR,
    EX005_EXERCISE_INPUTS,
    EX005_EXPECTED_SINGLE_LINE,
    EX005_FULL_NAME_EXERCISE,
    EX005_INPUT_PROMPTS,
    EX005_MIN_EXPLANATION_LENGTH,
    EX005_NOTEBOOK_PATH,
    EX005_PLACEHOLDER_PHRASES,
    EX005_PROFILE_EXERCISE,
)
from tests.exercise_expectations.ex006_sequence_modify_casting import (
    EX006_EXPECTED_OUTPUTS,
    EX006_INPUT_EXPECTATIONS,
    EX006_NOTEBOOK_PATH,
)
from tests.exercise_expectations.types import Ex006InputExpectation

__all__ = [
    "EX001_FUNCTION_NAME",
    "EX001_NOTEBOOK_PATH",
    "EX001_TAG",
    "EX002_EXPECTED_MULTI_LINE",
    "EX002_EXPECTED_NUMERIC",
    "EX002_EXPECTED_PRINT_CALLS",
    "EX002_EXPECTED_SINGLE_LINE",
    "EX002_NOTEBOOK_PATH",
    "EX003_EXPECTED_INPUT_MESSAGES",
    "EX003_EXPECTED_PROMPTS",
    "EX003_EXPECTED_STATIC_OUTPUT",
    "EX003_NOTEBOOK_PATH",
    "EX003_ORIGINAL_PROMPTS",
    "EX004_EXPECTED_SINGLE_LINE",
    "EX004_FORMAT_VALIDATION",
    "EX004_MIN_EXPLANATION_LENGTH",
    "EX004_NOTEBOOK_PATH",
    "EX004_PLACEHOLDER_PHRASES",
    "EX004_PROMPT_STRINGS",
    "EX005_AVERAGE_DIVISOR",
    "EX005_EXERCISE_INPUTS",
    "EX005_EXPECTED_SINGLE_LINE",
    "EX005_FULL_NAME_EXERCISE",
    "EX005_INPUT_PROMPTS",
    "EX005_MIN_EXPLANATION_LENGTH",
    "EX005_NOTEBOOK_PATH",
    "EX005_PLACEHOLDER_PHRASES",
    "EX005_PROFILE_EXERCISE",
    "EX006_EXPECTED_OUTPUTS",
    "EX006_INPUT_EXPECTATIONS",
    "EX006_NOTEBOOK_PATH",
    "Ex006InputExpectation",
]
