"""Shared expectations for notebook exercises."""

from __future__ import annotations

from tests.exercise_expectations.types import Ex006InputExpectation
from tests.notebooks.ex001_sanity.expectations import (
    EX001_FUNCTION_NAME,
    EX001_NOTEBOOK_PATH,
    EX001_TAG,
)
from tests.notebooks.ex002_sequence_modify_basics.expectations import (
    EX002_EXPECTED_MULTI_LINE,
    EX002_EXPECTED_NUMERIC,
    EX002_EXPECTED_PRINT_CALLS,
    EX002_EXPECTED_SINGLE_LINE,
    EX002_MODIFY_STARTER_BASELINES,
    EX002_NOTEBOOK_PATH,
)
from tests.notebooks.ex003_sequence_modify_variables.expectations import (
    EX003_EXPECTED_INPUT_MESSAGES,
    EX003_EXPECTED_PROMPTS,
    EX003_EXPECTED_STATIC_OUTPUT,
    EX003_MODIFY_STARTER_BASELINES,
    EX003_NOTEBOOK_PATH,
    EX003_ORIGINAL_PROMPTS,
)
from tests.notebooks.ex004_sequence_debug_syntax.expectations import (
    EX004_EXPECTED_SINGLE_LINE,
    EX004_FORMAT_VALIDATION,
    EX004_MIN_EXPLANATION_LENGTH,
    EX004_MODIFY_STARTER_BASELINES,
    EX004_NOTEBOOK_PATH,
    EX004_PLACEHOLDER_PHRASES,
    EX004_PROMPT_STRINGS,
)
from tests.notebooks.ex005_sequence_debug_logic.expectations import (
    EX005_AVERAGE_DIVISOR,
    EX005_EXERCISE_INPUTS,
    EX005_EXPECTED_SINGLE_LINE,
    EX005_FULL_NAME_EXERCISE,
    EX005_INPUT_PROMPTS,
    EX005_MIN_EXPLANATION_LENGTH,
    EX005_MODIFY_STARTER_BASELINES,
    EX005_NOTEBOOK_PATH,
    EX005_PLACEHOLDER_PHRASES,
    EX005_PROFILE_EXERCISE,
)
from tests.notebooks.ex006_sequence_modify_casting.expectations import (
    EX006_EXPECTED_OUTPUTS,
    EX006_INPUT_EXPECTATIONS,
    EX006_MODIFY_STARTER_BASELINES,
    EX006_NOTEBOOK_PATH,
)
from tests.notebooks.ex007_data_types_debug_casting.expectations import (
    EX007_EXPECTED_STATIC_OUTPUTS,
    EX007_INPUT_CASES,
    EX007_MIN_EXPLANATION_LENGTH,
    EX007_MODIFY_STARTER_BASELINES,
    EX007_NOTEBOOK_PATH,
    EX007_PLACEHOLDER_PHRASES,
)

__all__ = [
    "EX001_FUNCTION_NAME",
    "EX001_NOTEBOOK_PATH",
    "EX001_TAG",
    "EX002_EXPECTED_MULTI_LINE",
    "EX002_EXPECTED_NUMERIC",
    "EX002_EXPECTED_PRINT_CALLS",
    "EX002_EXPECTED_SINGLE_LINE",
    "EX002_MODIFY_STARTER_BASELINES",
    "EX002_NOTEBOOK_PATH",
    "EX003_EXPECTED_INPUT_MESSAGES",
    "EX003_EXPECTED_PROMPTS",
    "EX003_EXPECTED_STATIC_OUTPUT",
    "EX003_MODIFY_STARTER_BASELINES",
    "EX003_NOTEBOOK_PATH",
    "EX003_ORIGINAL_PROMPTS",
    "EX004_EXPECTED_SINGLE_LINE",
    "EX004_FORMAT_VALIDATION",
    "EX004_MIN_EXPLANATION_LENGTH",
    "EX004_MODIFY_STARTER_BASELINES",
    "EX004_NOTEBOOK_PATH",
    "EX004_PLACEHOLDER_PHRASES",
    "EX004_PROMPT_STRINGS",
    "EX005_AVERAGE_DIVISOR",
    "EX005_EXERCISE_INPUTS",
    "EX005_EXPECTED_SINGLE_LINE",
    "EX005_FULL_NAME_EXERCISE",
    "EX005_INPUT_PROMPTS",
    "EX005_MIN_EXPLANATION_LENGTH",
    "EX005_MODIFY_STARTER_BASELINES",
    "EX005_NOTEBOOK_PATH",
    "EX005_PLACEHOLDER_PHRASES",
    "EX005_PROFILE_EXERCISE",
    "EX006_EXPECTED_OUTPUTS",
    "EX006_INPUT_EXPECTATIONS",
    "EX006_MODIFY_STARTER_BASELINES",
    "EX006_NOTEBOOK_PATH",
    "EX007_EXPECTED_STATIC_OUTPUTS",
    "EX007_INPUT_CASES",
    "EX007_MIN_EXPLANATION_LENGTH",
    "EX007_MODIFY_STARTER_BASELINES",
    "EX007_NOTEBOOK_PATH",
    "EX007_PLACEHOLDER_PHRASES",
    "Ex006InputExpectation",
]
